# These are supported funding model platforms

github: [cloudbadal007]  # Your GitHub username
patreon: cloudpankaj      # Your Patreon username
ko_fi: cloudpankaj        # Your Ko-fi username
custom: ['https://www.buymeacoffee.com/cloudpankaj']  # Custom sponsor link
